.IX Title "GDC 1"
.TH GDC 1
.\" Always turn off hypenation; it makes way too many mistakes
.\" in technical documents. :~)
.nh
.SH "NAME"
gdc - D Front End for GCC
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
gdc [-switches] [-o outfile] files.d ...
.PP
For any given input file, the file name suffix determines what kind of
compilation is done:
.IP "\fIfile\fR.d" 4
.IX Item "file.d"
.PD
D source files
.IP "\fIfiles\fR.di" 4
.IX Item "file.di"
D interface files
.IP "\fIfiles\fR.o" 4
.IX Item "files.o"
Object files to link in
.IP "\fIfiles\fR.a" 4
.IX Item "files.a"
Library files to link in
.SH OPTIONS
.IX Header "OPTIONS"
.SS "Option Summary"
.IX Subsection "Option Summary"
Only the new options are listed here; gdc accepts mostly the same
options as gcc.  Most of these have both positive and negative forms;
the negative form of -ffoo would be -fno-foo.
This manual documents only one of these two forms, whichever one is
not the default.
.IP "\fBD Language Options\fR" 4
.IX Item "D Language Options"
.\" TODO: write longer/more concise descriptions for each option.
.IP "\fB-frelease\fR" 4
.IX Item "-frelease"
Compile release version.
.IP "\fB-funittest\fR" 4
.IX Item "-funittest"
Compile in unittest code.
.IP "\fB-fno-assert\fR" 4
.IX Item "-fno-assert"
Turn off runtime code for assert()'s.
.IP "\fB-fno-invariants\fR" 4
.IX Item "-fno-invariants"
Turn off runtime code for invariant()'s.
.IP "\fB-fno-in\fR" 4
.IX Item "-fno-in"
Turn off runtime code for in() contracts.
.IP "\fB-fno-out\fR" 4
.IX Item "-fno-out"
Turn off runtime code for out() contracts.
.IP "\fB-fno-bounds-check\fR" 4
.IX Item "-fno-bounds-check"
Turns off array bounds checking for all functions.
.IP "\fB-fdebug-c\fR" 4
.IX Item "-fdebug-c"
With -g, generate C debug information.
.IP "\fB-fdeprecated\fR" 4
.IX Item "-fdeprecated"
Allow use of deprecated features.
.IP "\fB-fd-verbose\fR" 4
.IX Item "-fd-verbose"
Print information about D language processing to stdout.
.IP "\fB-fproperty\fR" 4
.IX Item "-fproperty"
For D2, enforce @property syntax.
.IP "\fB-fd-vtls\fR" 4
.IX Item "-fd-vtls"
List all variables going into thread local storage.
.IP "\fB-fignore-unknown-pragmas\fR" 4
.IX Item "-fignore-unknown-pragmas"
Ignore unsupported pragmas.
.IP "\fB-femit-templates\fR[=all|normal|private|none|auto]" 4
.IX Item "-femit-templates[=all|normal|private|none|auto]"
Control template emission.
These are the supported options:
.RS 4
.IP "\fBall\fR" 2
.IX Item "all"
Emit templates, expecting multiple copies to be merged by the linker.
.IP "\fBnormal\fR" 2
.IX Item "normal"
Emits templates, but only if the compiler determines that it needs to.
.IP "\fBprivate\fR" 2
.IX Item "private"
Emit templates, but make them private to the translation unit.
The executable will have multiple copies of code and data.
.IP "\fBnone\fR" 2
.IX Item "none"
Do not emit templates at all.
.IP "\fBauto\fR" 2
.IX Item "auto"
For targets that support templates, the "all" mode is used.
Otherwise, the "private" mode is used.
.RE
.IP "\fB-fdebug\fR[=level|ident]" 4
.IX Item "-fdebug[=level|ident]"
Compile in debug code into the program.
These are supported options:
.RS 4
.IP "\fBlevel\fR" 2
.IX Item "level"
Compile in debug code <= level.
.IP "\fBident\fR" 2
.IX Item "ident"
Compile in debug code identified by ident.
.RE
.IP "\fB-fdeps=\fR<filename>" 4
.IX Item "-fdeps=<filename>"
Write module dependencies to filename.
.IP "\fB-fmake-deps=\fR<filename>" 4
.IX Item "-fmake-deps=<filename>"
Write makefile dependency output to the given file.
.IP "\fB-fmake-mdeps=\fR<filename>" 4
.IX Item "-fmake-mdeps=<filename>"
Like -fmake-deps=<file> but ignore system header files.
.IP "\fB-fonly=\fR<filename>" 4
.IX Item "-fonly=<filename>"
Process all modules specified on the command line,
but only generate code for the module specified by the argument.
.IP "\fB-fversion=\fR<level|ident>" 4
.IX Item "-fversion=<level|ident>"
Compile in version code >= level or identified by ident.
.IP "\fB-fintfc\fR" 4
.IX Item "-fintfc"
Generate D interface files.
.IP "\fB-fintfc-dir=\fR<directory>" 4
.IX Item "-fintfc-dir=<directory>"
Write D interface files to directory.
.IP "\fB-fintfc-file=\fR<filename>" 4
.IX Item "-fintfc-file=<filename>"
Write D interface file to filename.
.IP "\fB-fdoc\fR" 4
.IX Item "-fdoc"
Generate documentation.
.IP "\fB-fdoc-dir=\fR<directory>" 4
.IX Item "-fdoc-dir=<directory>"
Write documentation file in directory.
.IP "\fB-fdoc-file=\fR<filename>" 4
.IX Item "-fdoc-file=<filename>"
Write documentation file to filename.
.IP "\fB-fdoc-inc=\fR<filename>" 4
.IX Item "-fdoc-inc=<filename>"
Include a Ddoc macro file.
.IP "\fB-fXf=\fR<filename>" 4
.IX Item "-fXf=<filename>"
Write JSON file to filename.
.IP "\fB-fdump-source\fR" 4
.IX Item "-fdump-source"
Dump decoded UTF-8 text from source.
.SH "SEE ALSO"
.IX Item "SEE ALSO"
.BR gcc(1)
.SH "AUTHOR"
.IX Header "AUTHOR"
.PD 0
GDC was written by, and copyright:
  David Friedman (C) 2004-2007

Maintained by:
  Iain Buclaw (C) 2010-2011
.PD
