#!/bin/sh

base=`basename $1`
src=$base.c
exe=$base.exe

echo '#include "x3.h"' > $src
echo 'void x3_go() {' >> $src
cat "$1" >> $src
echo '}' >> $src

shift

if $CC_FOR_BUILD -g -o $exe $src config/x3.o config/x3main.o $BUILD_LIBIBERTY; then
    echo "** x3: running ./$exe" "$@"
    ./$exe -v -t tmp$base "$@"
    result=$?
else
    result=1
fi

if test $result -eq 0; then
    rm -f $exe $src
fi

exit $result
