.TH rdmd 1
.SH NAME
rdmd - DMD Script Shell
.SH SYNOPSIS
.B rdmd
.I [dmd arguments]
.I [rdmd arguments]
progfile.d
.I [program arguments]
.SH OPTIONS
.IP --help
This message
.IP --force
Force re-compilation of source code [default = do not force]
.IP --verbose
Show detailed info of operations [default = do not show]
.IP --compiler=(dmd|gdmd)
Specify compiler [default = same compiler that compiled rdmd]
.IP --tmpdir=tmp_dir_path
Specify directory to store cached program and other temporaries [default = /tmp]
.SH NOTES
dmd or gdmd must be in the current user context $PATH

rdmd does not support execution of D source code via stdin

rdmd will only compile and execute files with '.d' or '.ds' file extensions
.SH AUTHOR
written by Dave Fladebo (linux version)
and Robert Mariottini (Windows version)
.SH COPYRIGHT
released into the public domain
